### ISSUE TITLE
Subscription event publishes once

### ISSUE THREAD

**Issue by burntblark** [burntblark/ngx-sails-socketio#27]
When subscribing to an event, the update comes just once. Suspecting it is caused by the use of promises.

**Comment by jogboms** [comment]
I have actually thought about converting all our promises to observables. It makes sense since it'll always be used within an angular app.

**Comment by burntblark** [comment]
I was tempted to do the same but I thought the results come once anyway. That sounds like a promise. However if we make use of `Subject`, we can pass all fetches through a stream which is then subscribed to.

**Comment by jogboms** [comment]
I feel its technically sound if everything returns observables, seeing how we always have to convert the returned promises to observables again in our codes in order to do behavior compositions.

I can get this done.
