### ISSUE TITLE
Repository in maintenance

### ISSUE THREAD

**Issue by abalad** [burntblark/ngx-sails-socketio#35]
Hi. I'm starting a project with Angular + SAILS and I'm looking for a library that supports this stack. I really liked the approach that you created mainly from the issue of Models.

However I am in doubt as to the maintenance of the repository, you still intend to work on it? If so I can contribute a lot to your project reporting Bugs and even with PullRequests.

**Comment by burntblark** [comment]
Hi @abalad,

Sorry for late response. Thank you for your comments. Will be glad to get PRs from you. The repository is still under maintenance it is not just updated lately. I have a more recent copy locally and will update it ASAP. Hope this is not coming too late.

**Comment by abalad** [comment]
I made a fork and upgraded it to the new version of Angular and I'm using my version that made the Fork if you want it to send a PR. I may be sending

**Comment by tleperou** [comment]
Sounds good! Thanks for your effort guys. @abalad I am interested :+1:

**Comment by jogboms** [comment]
@burntblark see here.

**Comment by abalad** [comment]
@tleperou Since when I made the Fork I created a lot of things, I even created some missing requests, as the **replace**.

**Comment by tleperou** [comment]
Noted @abalad thanks. I am upgrading the repo and demo to the latest Angular and Rxjs versions. May I fork and PR?

**Comment by jogboms** [comment]
Sure @tleperou, it will be for all our benefits

**Comment by tleperou** [comment]
Guys, that's available on my fork, branch AngRx6-upgrade. **Need to test before merging**.

I got an issue on requesting data. 
Queries don't get anymore a response type of `SailsReponse`. So, for example:
```
// sails.query.ts, from line 23
// ... method find()
        return this.request.get(`/${this.model.getEndPoint()}`).pipe(map(res => {
            if (res.isOk()) {
                return SailsModel.unserialize<T>(this.modelClass, res.getData()) as T[];
            }
            throw res;
        }));
// ...
```

`res` is the body of the request's response, which does not inherit `isOk` from `SailsReponse`.

Change this:
```
// sails.js line 178
obs.next(response.getBody());
```
to 
```
// sails.js line 178
obs.next(response);
```
does the job. 

However, I feel I'm missing something ... right?

**Comment by abalad** [comment]
The changes that fis in this file were these: https://gist.github.com/abalad/29b9c4900de17e5e811b8a505a6085f3

**Comment by tleperou** [comment]
Sounds good me then, I did same.

**Comment by burntblark** [comment]
Hello guys, I see awesome job here. Thanks to @abalad for reviving this repo. @tleperou thanks for the contribution. I just merged your PR and we are now Angular 6 compatible! I'd have to setup a test though so next time we'd know if we have a breaking change. My local copy has got the update to Angular 6, along with compatibility with Sails v1.0.2. I hope I'd get the courage to get this up here. Once again, I appreciate your efforts and looking forward to a better repo.

**Comment by abalad** [comment]
@burntblark Thank you.

It would be a great pleasure to be able to help, I even created some other requests that were missing like [populate](https://sailsjs.com/documentation/reference/blueprint-api/populate-where), [replace ](https://sailsjs.com/documentation/reference/blueprint-api/replace)I do not know if it is the best way, but I followed the same pattern that you were using.

https://gist.github.com/abalad/a9b135b69b031c286f7ab54be10c5592

**Comment by abalad** [comment]
What I would recommend is to use the same names as the BLUEPRINT API.
Well I realized that some query methods are using the BLUEPRINT standard and others following the Waterline standard.

- addTo
- create
- destroy
- findOne
- find
- populate
- remove
- replace
- update

Or create following the Waterline pattern

- addToCollection
- archive
- create
- destroy
- find
- findOne
- findOrCreate
- removeFromCollection
- replaceCollection
- update

**Comment by burntblark** [comment]
@abalad Great! I think adding the Blueprint methods is a better way forward as we are dealing with sails. Sails already abstracted Waterline so we do not need to present it in this library. This may produce some breaking change or deprecated methods. Either way it is a good way forward. Looking forward to a PR.

**Comment by burntblark** [comment]
@abalad after a bit more thought I think your suggestion should come as a service (more like a generic abstract class `ModelService<T>`). I am saying this because not all requests are made to a sails model. The basic verbs are sufficient for the `SailsRequest` object as it is. Anyone needing to make requests to a model using the Blueprint can inherit this class.

**Comment by abalad** [comment]
However, I already think that the basic BLUEPRINT methods that are allowed through routes should be ready to use. https://sailsjs.com/documentation/concepts/blueprints/blueprint-routes

So I think using the same names https://sailsjs.com/documentation/reference/blueprint-api
it would be nice Because as LIB is for Sails I think it should follow the same nomenclature.

I say this because there are some methods like **SAVE**
**https://github.com/burntblark/ngx-sails-socketio/blob/fcacfbd9ff5db34e34487a7af22ede2ad7fada5f/src/sails.query.ts#L43** 

**REMOVE** Which in the case I believe should be called destroy.
Because the remove in BLUEPRINT is used for something else
https://github.com/burntblark/ngx-sails-socketio/blob/fcacfbd9ff5db34e34487a7af22ede2ad7fada5f/src/sails.query.ts#L83

AND  **findById**  that does not meet any Waterline or blueprint nomenclature. https://github.com/burntblark/ngx-sails-socketio/blob/fcacfbd9ff5db34e34487a7af22ede2ad7fada5f/src/sails.query.ts#L33

**Comment by burntblark** [comment]
@abalad I see your point now. I thought they were going to be implement along with the HTTP verbs. If it is on the `SailsQuery` object then I think it is an awesome idea.

**Comment by burntblark** [comment]
Closing this issue as the topic is no longer relevant.
